### ISSUE TITLE
pebbljs loader bootstrap

### ISSUE THREAD

**Issue by msowka** [pebble/pebblejs#92]
Question, and at most a request for enhancement: is it possible to bootstrap CJS-based (?) loader & its packages outside of the pebblejs build / runtime? In developing a pebblejs app I intend to test (and more generally develop) the supporting modules outside of the pebble(js) environment. I would like to do this with jasmine, and do so using the pebblejs loader.require mechanism.

I have setup a jasmine SpecRunner.html that includes all the required jasmine js/css, then continues to include the loader.js and <appmodule.js> files in the html>head>script tags. require is not exported to the global context and so my modules that require('ajax'), for example, don't work.

Reading loader.js and wrapping my head around the cjs/amd innards (more than I like, perhaps) I see that the pebblejs mechanism first requires that packages be loader.defined. This seems to be done in the js bootstrapping scripts that wscript generates at 'pebble build' time.

Is there a way to easily setup my js tests, to use loader.js such that I can test my modules with their pebblejs lib dependencies & module interdependencies etc, ?

Appreciate any suggestions.

**Comment by Meiguro** [comment]
Hey @mswoka, I'm glad you're looking into setting up tests!

That is right, loader.define is what defines a package. loader.js is not necessarily AMD even though it has a define function. The wrapping actually occurs in wscript, but you don't need to know that.

The important bit is that packages written for loader.js are supposed to be exactly as if they were written for node.js, minus all the node.js globals such as global and its native library. This means if you wanted to use modules written for pebble.js/loader.js, you would do the same thing you would do with node.js modules. I believe you can use [browserify](http://browserify.org/), but you'll likely have to muck with a few options, such as setting up many default paths since loader.js doesn't require the './' at the start of the path string. You could say that loader.js is just a lightweight version of browserify made for PebbleKit JS.

If that doesn't work out for you for any reason, you can also write your modules as non-require compatible. i.e
```
if (typeof require !== 'undefined') {
  // require
} else {
  // access globals
}

if (typeof module !== 'undefined') {
  // export
} else {
  // globally export
}
```

Regardless, you can consider this ticket a feature request for adding test support.

**Comment by msowka** [comment]
Yes, I think I understand a bit better from further poking around and your explanation. I've made some progress, and will make a point of having things polished enough to submit as pr.

I had selected to use [jasmine_egg](http://jasmine.github.io/2.3/python_egg.html) as python is already used throughout the pebble system, and it's much simpler than the jasmine-provided html template. Having realized how define is *actually* use in pebblejs, I think the easiest solution would be to use pebble-js-app.js as built by wscript. (Why bother with browserify?)

The catch of course is the Pebble object. Pebble ideally should be stubbed/mocked for its testing sake (long-term suggestion), or for now simply commented out of the pebble-js-app.js as it's copied to the jasmine spec/javascript/ source directory. I've had some success with this. Couple of related / tangent questions before I get a chance to hack on this some more:
- Where is the 'require' actually exported into the global scope, is it the one-time flow through in loader.getPackage; and if so which path/package is that normally requested in, 'main.js', ?
- Why are the package lineno recorded on define, ie when would a package be loader.getPackageByLineno?

**Comment by Meiguro** [comment]
I'm glad you've chosen to use loader.js, since I agree that something as PR shouldn't use browserify. I made the suggestion in case digging into pebble.js internals was cumbersome.

*Where is the 'require' actually exported into the global scope, is it the one-time flow through in loader.getPackage; and if so which path/package is that normally requested in, 'main.js', ?*

`require` is a local variable passed into a function. This is to allow the module to lookup its dependencies starting by the relative path first which is different for each module. Looking at `src/build/src/js/pebble-js-app.js` you will see that loader.define is passed a function that expects `exports, module, require` as parameters. The closest thing to a global require is loader.require, but essentially there is no global require.

*Why are the package lineno recorded on define, ie when would a package be loader.getPackageByLineno?*

As of SDK 3.2.1, the pebble mobile apps do not support multiple JavaScript files in a single app nor does it support source maps. This causes exceptions to be filled with line references to `pebble-js-app.js` which is not useful if you've concatenated the files. There is a sister module safe.js which uses the loader.getPackageByLineno to translate the stack trace to something readable.

**Comment by matism** [comment]
Lieber E-Mail Schreiber,

ich bin bis einschließlich 9. September auf Urlaub.

Ihre E-Mail wurde nicht weitergeleitet und wird erst nach meinem Urlaub beantwortet. In dringenden Fällen kontaktieren Sie bitte meinen Kollegen Markus Pirker unter markus.pirker@simplease.at.

Herzlichen Dank,
Mathias Placho

**Comment by msowka** [comment]
Thanks for further explanation M. I've got a basic setup working now, testing my service module for now. Yes, it's a bit different, but the pebblejs loader system is quite clever. I choose it mostly to keep it simple :).

Yes, require being a module.loader function argument makes perfect sense now. The only catch is (and this may be a bug in your current HEAD or in my grokking the project or js) the loader.require line that calls the module.loader passes only two arguments (module, function(path) [require]). In order to get this working I changed loader.js:L42 (commit 006dbc8) to:
`module.loader(module.exports, module, function(path) { return loader.require(path, module); });`

Perhaps I'm still missing something, as otherwise it would be a fluke that this works in actual pebble runtime... (?)

In my jasmine [module]Spec.js tests I then simply `var require = __loader.require;` for convenience, and define my tests suits/cases using the require construct. <shrug> This does the trick.

I've had to also define a pebbleStub.js, which includes a stub of the Pebble object and addEventListener function just to bootstrap without errors. I don't believe any of this amounts to much of a commit yet (in terms of pebblejs contribution), but I will keep you posted.

Yes, the line-numbers concept makes sense now too. It is awfully frustrating that at least on cloudpebble there is no line numbers printed out on error. Perhaps this is related. Why was this move to single js file made, technical reasons or target platform requirements, ?

**Comment by Meiguro** [comment]
I'm happy to hear you have something working! Thanks for the kind words, I wanted to keep the number of lines as low as possible for loader.js since I envisioned it could later be used for non-pebble.js projects too.

*It is awfully frustrating that at least on cloudpebble there is no line numbers printed out on error.*

Is this true as of today? Or are you posting about non-pebble.js PebbleKit JS projects? For pebble.js, I try to support CloudPebble as much as possible. I tried `var a = c + d;` and obtained the following stacktrace in "View Logs":

    [PHONE] pebble-app.js:?: JavaScript Error:
    ReferenceError: c is not defined
        at Object.loader (app.js:168:9)
        at Object.loader.require (loader.js:44:10)
        at require (loader.js:41:48)

If you're not getting line numbers, post a gist of a minimal example, I could be missing an asynchronous try catch.

*Perhaps this is related. Why was this move to single js file made, technical reasons or target platform requirements, ?*

From pebble.js' perspective, it's a limitation of the phone apps. I sometimes make bugs in the firmware and mobile apps sound worse than normal so that they get promptly fixed, but they aren't usually that bad ;). Although multiple file support is a very desirable feature, it is still a feature that can be dropped if other unforeseen problems need to be addressed. It's the base features that make projects like pebble.js possible at all that is most important, such as bug free app messaging.

At the time of PebbleKit JS' inception, everything was in a state that could change. After that, the phone apps have had to be in a mode of stabilization and coordination with new firmware features. Eventually there will be time for such features, hopefully. We've had direct CloudPebble pbw installation added after for example. In any case, I speak entirely from the point of view of an observer.

**Comment by pautomas** [comment]
I worked in a small sample app that shows how to support Pebble.loader on PebbleKIT JS apps. I've been using it on my app for a while and it seems to work well with libraries like lodash or promiseJS.

 It doesn't support the correct line number in the error logs yet but is something I have in the backlog.

Please take a look (and add any issue) to https://github.com/pautomas/pebblekit-js-require
