### ISSUE TITLE
Error loading menu icons

### ISSUE THREAD

**Issue by fletchto99** [pebble/pebblejs#97]
When I load a menu with ~20 items, each having an icon, then push another item to the window stack, such as a Card, and finally close that window by pressing back, the following error occurs:

``` javascript
TypeError: undefined is not a valid argument for 'in' (evaluating 'name in def')
    at prop (lib/struct.js:231:17)
    at image (ui/simply-pebble.js:930:50)
    at onLoad (ui/imageservice.js:92:22)
    at load (ui/imageservice.js:106:11)
    at resolve (ui/imageservice.js:121:60)
    at ImageType (ui/simply-pebble.js:58:32)
    at lib/struct.js:161:32
    at menuItem (ui/simply-pebble.js:1040:10)
    at _resolveItem (ui/menu.js:168:30)
    at _preloadItems (ui/menu.js:177:22)
    at _resolveSection (ui/menu.js:158:25)
    at _prop (ui/menu.js:41:25)
    at _show (ui/window.js:89:13)
    at _show (ui/menu.js:31:31)
    at _show (ui/windowstack.js:44:13)
    at remove (ui/windowstack.js:87:15)
    at emitHide (ui/windowstack.js:116:14)
    at onPacket (ui/simply-pebble.js:1248:27)
    at onAppMessage (ui/simply-pebble.js:1291:26)
```

Visually nothing is affected and the app is still usable.

Here is the app that I am building which causes this issue: https://github.com/fletchto99/pebble-appstore

**Comment by fletchto99** [comment]
Just an update. This same issue appears to crash the app on the aplite platform.
